name: Flask app CI/CD pipeline

on:
    push:
        branches: [ main ]
        paths-ignore:
          - 'README.md'
          - 'flask-app/**'
          - 'helm-charts/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64, linux/arm64/v8
                push: true
                tags: progerjkd/flask-app:latest
